repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-json

- repo: https://github.com/pycqa/isort
  rev: 5.5.2
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black

- repo: https://github.com/pycqa/flake8
  rev: 3.8.3
  hooks:
    - id: flake8
